### ISSUE TITLE
Hierarchical Clustering of Compounds

### ISSUE THREAD

**Issue by jmabbott40** [girke-lab/chemminetools#164]
Hello, hope all is going well. My name is Josh and I am a PhD student at the University of Colorado. I am new to using R, but have found your instructions and program fairly easy to use. I do have one issue, that I'm hoping you can help me with.

If I use the browser interface to do clustering, the resulting heatmap is beautiful, but I'm limited to 30 compounds. I was able to do this in R Studio as well with an expanded data set, but my heatmap looks pretty bad and it is not as intuitive to understand as the one generated in the web server. Is there any tips for how to simplify my heatmap to mimic the webserver one with ~100 compounds. I'm doing a high-throughput screen and would like to easily visualize SAR among my hits.

Thanks for your time,
Josh Abbott

**Comment by tgirke** [comment]
Here are some basic instructions for cluster analysis in R: http://bit.ly/2s9Hium. In addition, you may want to consult the clustering sections in the ChemmineR vignette. In general, both the online (Chemmine Tools) and R (ChemmineR) versions of the software allow you to cluster much larger numbers of compounds than 30-100.
