### ISSUE TITLE
pubchem pre-built sqlite db

### ISSUE THREAD

**Issue by senars00** [girke-lab/chemminetools#166]
BioassayR in Bioconductor link to download sqlite prebuilt pubchemDB:
 http://chemmine.ucr.edu/bioassayr

shows this message;
The page you requested could not be found. Please try again, or send us a support e-mail via the contact link on the front page.

is the DB in a different location?
tx
Sergio

**Comment by TylerBackman** [comment]
Hi Sergio,

Sorry it seems to have disappeared from ChemMine Tools when it was migrated to AWS. Perhaps @tgirke or @girke-lab/kevinhoran can recover the page from the old server.

In the meantime you can find a link to the database file here:
biocluster.ucr.edu/~tbackman/bioassayR/pubchem_protein_only.sqlite

You will likely want to confirm that the md5sum is correct after downloading this 7.8 Gb file:
294c1e7e27ffd8ed37411087e15474af

Sincerely,
Tyler

**Comment by khoran** [comment]
link fixed
