### ISSUE TITLE
Where can I locate the bioassayR database?

### ISSUE THREAD

**Issue by acnash** [girke-lab/chemminetools#167]
I am reading the BioassayR guide on prebuilt PubChem Bioassay DBs:

https://www.bioconductor.org/packages/release/bioc/vignettes/bioassayR/inst/doc/bioassayR.html#prebuilt-database-example-investigate-activity-of-a-known-drug

And, the embedded link to the database http://chemmine.ucr.edu/bioassayr/ does not work.

Could anyone please provide an updated link?

Thanks
Anthony

**Comment by TylerBackman** [comment]
Hi Anthony,

Sorry it seems to have disappeared from ChemMine Tools when it was migrated to AWS. Perhaps @tgirke or @khoran can recover the page from the old server.

In the meantime you can find a link to the database file here:
[http://biocluster.ucr.edu/~tbackman/bioassayR/pubchem_protein_only.sqlite](http://biocluster.ucr.edu/~tbackman/bioassayR/pubchem_protein_only.sqlite)

You will likely want to confirm that the md5sum is correct after downloading this 7.8 Gb file:
294c1e7e27ffd8ed37411087e15474af

Sincerely,
Tyler

**Comment by acnash** [comment]
Thank you, Tyler,


Very helpful. The link worked.


Thanks again

Anthony


Kind regards
Dr Anthony Nash PhD MRSC

Senior Research Scientist
Department of Physiology, Anatomy, and Genetics
University of Oxford
https://www.dpag.ox.ac.uk/

RMCR Kellogg College
University of Oxford
http://www.kellogg.ox.ac.uk/

________________________________
