### ISSUE TITLE
Save data from widget table

### ISSUE THREAD

**Issue by parknsn2** [girke-lab/chemminetools#168]
When I try to save data from the widget table, nothing is happening. I would like to export the numbers to an excel file. Thank you

**Comment by khoran** [comment]
I'm not sure what you mean by "widget table". Can you tell me what page you are on, or what tool you had just run? Thanks.

**Comment by parknsn2** [comment]
When I perform hierarchical clustering and open the table to see the actual values. I ended up finding a work-around (It works on firefox but not on chrome.)

**Comment by khoran** [comment]
To clarify, when you click on the table icon (popup text "Show Data"), and then click on the floppy disk icon, then nothing happens right? I'm getting that behavior myself in chrome right now. I'll look into it.

**Comment by parknsn2** [comment]
Correct

**Comment by khoran** [comment]
This is fixed now.
