### ISSUE TITLE
can't download similarity sdf

### ISSUE THREAD

**Issue by rabyafarid** [girke-lab/chemminetools#170]
I perform similarity search using fingerprint algorithm. When I search for 200/1000 compounds, I am unable to download the sdf. I can only download till 100 compounds. Is it a bug in the system or something else?

**Comment by khoran** [comment]
Can you please let me know which function specifically your using? Some sample code re-creating the problem would also be helpful. You don't need to provide the sdf though. Thanks.

**Comment by rabyafarid** [comment]
I am using the fingerprint algorithm to search through pubchem. The search
results turn out fine. It is when I try downloading them that it says there
is a problem with download. Thisonly happens for more than 100 compounds.
I cam easily download if there are only 100 compounds.

**Comment by khoran** [comment]
This has been fixed now.
