### ISSUE TITLE
clustering a large number of compounds

### ISSUE THREAD

**Issue by sumuduleelananda** [girke-lab/chemminetools#171]
I want to cluster about ~20,000 compounds. When I tried to use the online server, it errors. How many compounds can the online server handle? Thank you.

**Comment by tgirke** [comment]
The maximum is set to 5,000 I believe. For 20,000 you want to use the corresponding R package called [ChemmineR](https://www.bioconductor.org/packages/release/bioc/html/ChemmineR.html).

**Comment by sumuduleelananda** [comment]
Thank you. I'll try ChemmineR.
