### ISSUE TITLE
ChemMine for polymers

### ISSUE THREAD

**Issue by O-iver** [girke-lab/chemminetools#178]
Hi,

I am a new user of ChemMine and very interested in using it for clustering polymers. Just not clear if ChemMine can do this. Or if I use the monomer from the polymer structure, can ChemMIne cluster them? 

Thank you very much.

**Comment by tgirke** [comment]
That would depend on what you want to show in the clustering results. Perhaps just try both and see which one makes more sense for your scientific question.
