### ISSUE TITLE
Error on uploading SMILES file (tab separated)

### ISSUE THREAD

**Issue by osire56** [girke-lab/chemminetools#179]
Hello,
I am trying to convert online a CID /tab/ SMILES strings file to get the corresponding SDF format that I need for clustering/ heatmap building among about 400 compounds.
[SMR.txt](https://github.com/girke-lab/chemminetools/files/3939118/SMR.txt)
Can you tell me what is going wrong ?
Thanks for your help
Olivier Sire

**Comment by tgirke** [comment]
Please follow the format requirements for SMILES files given on the upload [page](https://chemminetools.ucr.edu/myCompounds/addCompounds/). - Thomas
