### ISSUE TITLE
Structural Similarity Search

### ISSUE THREAD

**Issue by Fxotics** [girke-lab/chemminetools#188]
Hi,

Hope you are doing well. I am currently having an issue and I got me quite confused.
Last week I ran a Structural Similarity Search for one compound, using the PubChem Fingerprint algorithm (cutoff of 0.95 and max comounds 1000) and I obtained pretty reasonable results. Now, today I had to run again the search in order to export once more the data but this time the result was different... the search did not throw any similar structures, even when the program was giving other results last time I tried it.

I am wondering if this happens frequently? What might be the reason this is happening? Is it a problem with the server, the database or something else? Or is it a bug?

This is quite importanto for me since I rely on the results of the search in order to move forward with a project of mine.

Thank you,
Felipe

**Comment by khoran** [comment]
Internally, we use the PubChem PUG REST service, which seems to be failing right now. Every request is returning: 
Status: 500
Code: PUGREST.ServerError
Message: Can't see oe_license.txt
So we will have to wait for them to resolve the error. Sorry about that.

**Comment by khoran** [comment]
seems to be working again now.
