### ISSUE TITLE
Question about ChemmineR output

### ISSUE THREAD

**Issue by jljohnson2** [girke-lab/chemminetools#193]
Hello there! 

I am Jade Johnson, an M.S. student at San Diego State University, at this institution I am working in the Environmental Health laboratory. We are excited to use your tools to retrieve more structural information about a list of chemicals for one of our research projects. 
I have two questions because I encountered an inconsistency in two data set outputs (from ChemmineR and JoeLib). 

**Description of my problem:** From the same SMILES text input of 100+ chemicals, I used both tools, JoeLib and ChemmineR, and I found an inconsistency in the reported molecular weight, "MW", for all of the compounds. I compared JoeLib's listed MW with EPA Comptox's listed average MWs for the same chemicals and those matched, so I think JoeLib is correct. Then I compared ChemmineR's output for MW with JoeLib and EPA Comptox - and ChemmineR did not match up. It looked like ChemmineR consistently subtracted about 8 units from the average MW for each chemical. 

**2 Questions**:  Does ChemmineR's incorrect output for MW effect the algorithm for the other structural data output? In that case we can't use the data, unless is this something that you can fix?

Thank you! I look forward to your response. 

Best, 
Jade 
jljohnson2@sdsu.edu

**Comment by tgirke** [comment]
It could be that the Hydrogens are not added by default and/or present in your input. You can check this in ChemmineR [here](https://www.bioconductor.org/packages/release/bioc/html/ChemmineR.html) by adding the argument `addH=TRUE` under the `MW` function. If needed we could add the argument option to the web service. Depending on what formats you are working with in some SDF files (or some SMILES) the molecules are sometimes fully hydrogenated and in some other cases not.

**Comment by jljohnson2** [comment]
Thank you for getting back to me so quickly! 

Looking at it again, I now see the hydrogen atoms were not accounted for in the MF column, and the difference in MW does seem to be due to the missing hydrogen atoms. So I agree that is likely the problem. 

Could you please add the argument option to the web service?

Thank you!

**Comment by tgirke** [comment]
Sure we can. BTW: currently this affects only 3 simple descriptors: MW, MF and H count. The others will not change.

**Comment by jljohnson2** [comment]
Oh ok, that was my other question. Great to know. Thank you!

**Comment by tgirke** [comment]
The option to add hydrogens prior to computing the descriptors has been added. You'll fine on the bottom of the submission page after selecting ChemmineR properties [here](https://chemminetools.ucr.edu/tools/launch_job/Properties/).
