### ISSUE TITLE
Adding compounds: does it take long?

### ISSUE THREAD

**Issue by fermza** [girke-lab/chemminetools#202]
Hi! I have registered in ChemMine Tools, then I've trying to add compounds, but every attempt I've made takes very long. I am not sure if this is expected or maybe I am doing something wrong? I've tried either with PubChem CID lists, or SMILES (even individually). The upload job has been running for more than 12 hs now (using the server at https://chemminetools.ucr.edu/).
Any help to move forward and be able to run some tests with my compounds set will be greatly appreciated.

Best,
Fernando

**Comment by live568** [comment]
I am too facing the same issue. I have been using it for the past few months and it used to take hardly a minute.

**Comment by austinleong** [comment]
Thanks for bringing this issue to our attention. I'll be looking into this right away, and will update you accordingly. Sorry for the inconvenience.

- Austin

**Comment by khoran** [comment]
The work queue had gotten stuck. Should be working now. Sorry about that.
