### ISSUE TITLE
Chemmine tools working slow

### ISSUE THREAD

**Issue by live568** [girke-lab/chemminetools#205]
Hi,

The "structural similarity search" tool is working very slowly today. It is taking upto half an hour for a single compound. Please fix it at the earliest as I am working on an important project.

Thank you.

**Comment by austinleong** [comment]
Hello. Can you share the parameters of your Structural Similarity Search?

**Comment by live568** [comment]
Hi,

I am using compounds from workbench.
1 compound at a time.
Max compounds returned- 50/10
Similarity cutoff- 0.95

**Comment by austinleong** [comment]
Which algorithm? (Pubchem, ChEMBL EI, ChEMBL fingerprint)

**Comment by austinleong** [comment]
Hello again. The issue should be resolved now. Please try running the searches again and see if they complete within the expected time, and let us know.

**Comment by xiaodfeng** [comment]
Hi, I come across similar issue. I have sdf object containing 1800 compounds. I have to run the codes in for loop. The speed is slow, attached are my codes:
```
for (i in 1:length(sdf)){
  print(i)
  List[[i]] <- result(launchCMTool("OpenBabel Descriptors", sdf[i]))
}
```

**Comment by live568** [comment]
Apologies for late reply. Yes, it is working fine now. Thanks a lot.
