### ISSUE TITLE
Uploading SDF Files by batch

### ISSUE THREAD

**Issue by shariesk** [girke-lab/chemminetools#214]
Is there a way to upload multiple SDF files at once? I have also tried uploading a large SDF file with multiple compounds in it, but is there a specific format it has to be in so that it includes the file name instead of being called "unspecified..."?

**Comment by khoran** [comment]
A standard SDF file with entries separated by a line with just '$$$$' will allow you to upload multiple compounds at once. The name will be taken from the SDF entry, so make sure they have names given. Try this example file:
[myCompounds.txt](https://github.com/girke-lab/chemminetools/files/6704019/myCompounds.txt)
