### ISSUE TITLE
Similarity Workbench not working

### ISSUE THREAD

**Issue by gracekuan** [girke-lab/chemminetools#215]
Hello, 

My name is Grace Kuan. I am a toxicologist working for the State of Michigan's Department of Environment, Great Lakes, and Energy. I have been using ChemMine for some time now to work on PFAS research in increasing our agency's understanding of this environmental contaminant and to support pollution clean up efforts. Lately, I have not been able to get ChemMine to perform Tanimoto coefficient calculations through the similarity workbench. After I select the two compounds for comparison, the similarity results no longer appear. I'd like to submit a ticket to request fixing a potential bug with this function. Thank you!
Grace

**Comment by tgirke** [comment]
This working when using organic compounds with >= covalent bonds.
