### ISSUE TITLE
Error Message using ChemmineR

### ISSUE THREAD

**Issue by jljohnson2** [girke-lab/chemminetools#217]
Hello, 

I have 358 compounds I was able to add successfully using either a combination of SMILES strings or import from PubChem. 
I was able to successfully retrieve the JoeLib molecular descriptors for these compounds. 
However when I tried to use the ChemmineR tool, I ran into the following error message. 
"An error occured. Please try again, or send us a support e-mail via the contact link on the front page."

I tried again about 3 times. I will try again tomorrow, but am also sending this issue for some of your help with troubleshooting. 

Thank you, 

Jade

**Comment by austinleong** [comment]
Hello, I've been looking into your issue. Could you provide the list of compounds that you submitted into ChemmineR? Optionally, could you estimate the date and time (approximate hour should be sufficient, please include timezone) when you submitted the job? Thanks.

- Austin

**Comment by jljohnson2** [comment]
Hello Austin,

Thank you for getting back to me on this.
I attached the list of chemicals I submitted into ChemmineR.
If it is also helpful, I tried to submit the job on Monday (October 4,
2021) around 7PM (Pacific Time).

Best,

Jade
