### ISSUE TITLE
clustering compound library

### ISSUE THREAD

**Issue by barhoon** [girke-lab/chemminetools#219]
Hi.
I used Multidimensional Scaling (MDS) for clustering my compound library, but the clusters are very small and close together. I also need to have a representative for each cluster.
Is there a way for me to use the K-means clustering algorithm to cluster the attachment to the desired number and get a representative combination for each cluster? How can I do that? Thank you
https://usaupload.com/5fzk/cX-canvas.png

**Comment by tgirke** [comment]
Currently, such a feature is not available in the online tool. The binning clustering option is probably the closest for what you are suggesting. If you know a bit of R, then you could use the affiliated ChemmineR package ([here](https://www.bioconductor.org/packages/release/bioc/html/ChemmineR.html)) for such tasks.
