### ISSUE TITLE
Similarity Workbench

### ISSUE THREAD

**Issue by Mohammadradi** [girke-lab/chemminetools#220]
Hello, 

Trying to use the Similarity Workbench and looks that I need help. I don't know what to do after selecting two compounds from the grid. There is no intuitive step I think about. Is there a button somewhere I should clock on or I should wait? 
![Screenshot 2021-11-29 at 19 57 56](https://user-images.githubusercontent.com/13886936/143926846-29286666-b950-4d07-b568-a20891d83078.png)
Thanks for the help.

**Comment by tgirke** [comment]
You would need to upload and make comparisons among molecules that have at least one covalent bond and >=2 non-hydrogen atoms. The structural similarity algorithms implemented here expect compounds meeting these requirements. One could add this to the instructions and/or exception handling routines.
