### ISSUE TITLE
Problem in uploading numeric data

### ISSUE THREAD

**Issue by gianlucabiggi1** [girke-lab/chemminetools#228]
I am experiencing some problems in uploading a list of approximately 10.000 CIDs. The list is contained in the attachments below. Could you help me with this issue?

Best,

Gianluca

[cid.txt](https://github.com/girke-lab/chemminetools/files/8487707/cid.txt)

**Comment by tgirke** [comment]
This is too many. Use less than 1000. If you need 10,000 at once the use the our [ChemmineR](https://www.bioconductor.org/packages/release/bioc/html/ChemmineR.html) package in R.
