### ISSUE TITLE
Account Access

### ISSUE THREAD

**Issue by EdH66** [girke-lab/chemminetools#230]
Dear Girke-lab and ChemMine Team,

I would really like to access your tools but I am having problems with my account. I don't seem to receive any confirmation emails at ech66@medschl.cam.ac.uk from ChemMine and after trying to login unsuccessfully my account is now locked. Can we fix this?

thanks 
Ed Harding

**Comment by austinleong** [comment]
Hello Dr. Harding,

Thanks for bringing this issue to our attention. It's not immediately obvious what's wrong, so I've manually activated your account. Please try logging in again with the credentials you initially provided, and let us know if it works.

- Austin
