### ISSUE TITLE
Error when adding compounds by PubChem CIDs

### ISSUE THREAD

**Issue by Ifremer-RS** [girke-lab/chemminetools#243]
Hi Chemminetools team, 
Good day, I was trying to add compounds to My Compounds using CIDs so that I am able to have names for them, however, I always get an error. As my CIDs were directly downloaded from PubChem, I doubt it's a CID error and likely a failure to communicate with PubChem. Adding the compounds by SMILES was possible
[PubChem_compound_id_list.csv](https://github.com/girke-lab/chemminetools/files/11624699/PubChem_compound_id_list.csv)
, however, they do not have the proper chemical names, which would be helful for me when I perform a cluster analysis for Tanimoto similarity. Can you please help me? Thanks

**Comment by franksharptx** [comment]
Did they ever help you?

**Comment by tgirke** [comment]
Sorry for missing this message. We will fix this. In the meantime please add the pubchem cmp ids space separated at the end of the SMILES strings as shown [here](https://chemminetools.ucr.edu/myCompounds/addCompounds/).
