### ISSUE TITLE
Adding compounds always running

### ISSUE THREAD

**Issue by ToxRemeikas** [girke-lab/chemminetools#246]
Hello,
For the last week, I have been having issues with uploading compounds into the system to use in the similarity workbench.  When I upload the SMILES for the compounds the jobs get bumped as "running" and placed in past jobs.  In the beginning it would take a few minutes and they would pop up.  Over the week it has taken longer and now I have left it running overnight multiple times without it completing.  

I tried clearing my cache and cookies in the browser and restarted my computer fresh.  This did not work.

This issue occurs in Chrome and Firefox.

Is there anything I can do on my end?  My co-workers do not seem to be having this issue.

Thank you

**Comment by tgirke** [comment]
Thanks for letting us know. It should work again. The server needed a restart.  - T. Girke
