### ISSUE TITLE
Adding compounds

### ISSUE THREAD

**Issue by mubaric** [girke-lab/chemminetools#247]
Hello,

 I attempted to add several compounds using SMILES and CID ID (see below). However, the job has been running for around 24 hours. Is it supposed to take this long to upload 7 compounds?

CC1=CC(=NO1)NC(C)C | 55299575
CCCCCCCP(=O)(CC(C)C)C(C)CC | 11391326
C1CCC2=C(C1)C3=C(S2)N=CN(C3=N)CCO | 741885
CC(C)(C)C1=CC=C(C=C1)NC(=O)N2CCN(CC2)C3=C(C=CC=N3)Cl | 9929425
C1=CC(=CC=C1CN(C2=C(C=C(C=N2)C(F)(F)F)Cl)S(=O)(=O)C3=CC=C(C=C3)C(=O)O)OC(F)(F)F | 49783953
C1=CC(=C(N=C1)[C@H](C2=CC(=C(C=C2)OC(F)(F)F)F)NC(=O)C3=NC=C(C=C3)C(=O)O)F | 71144018
C[C@H](C1=CC=C(C=C1)F)N(CC2=CC(=CC=C2)C(=O)O)C(=O)C3=CC4=CC=CC=C4N=C3 | 60195662

**Comment by franksharptx** [comment]
I have the same problem!

**Comment by tgirke** [comment]
Thanks for letting us know. It should work again. The server needed a restart.  - T. Girke
