### ISSUE TITLE
Jobs run, but nothing happens

### ISSUE THREAD

**Issue by franksharptx** [girke-lab/chemminetools#248]
Hi. I submitted a similarity search and after 12 hours, it's still running. I can be patient, but when I tried to enter the list of 5 CIDs to submit "my compounds", I got an error message. I then decided to upload a single SDF file. Again, the job is running, for 15 minutes now, but nothing happens. I really want to use this software, because it should be able to do exactly what I'm looking for! Thank you most kindly in advance.

**Comment by tgirke** [comment]
Thanks for letting us know. It should work again. The server needed a restart.  - T. Girke
