### ISSUE TITLE
Similarity Workbench Still Not Working

### ISSUE THREAD

**Issue by ToxRemeikas** [girke-lab/chemminetools#250]
Hello again, 
My compounds are uploading great now, but when I click on two compounds in the similarity workbench to find out their MCS Tanimoto similarity, the wheel spins for a few seconds as if it is processing but then no result is provided.

I've tried this numerous times before and after clearing cookies, logged in and logged out.  

I've been using this program for years now and have not ever seen this issue. 
Please advise.

**Comment by tgirke** [comment]
I am not able to reproduce this problem. Could you send me the compounds where the problem occurs. Or first try it on some of the test compounds.

**Comment by ToxRemeikas** [comment]
Ok.  I just tested with a few other compounds that worked.

Could it be because they are inorganic? I thought I have used this program for inorganics before.

Here are the ones I was trying to run.  I was just going to use the MCS Tanimoto as further evidence for surrogate choice.

C(=O)([O-])[O-].[Mg+2]
[OH-].[OH-].[Mg+2]
[Mg+2].[Cl-].[Cl-]

Let me know what you find.

Thanks!

Deb Remeikas, M.A.
ToxServices
1367 Connecticut Ave, N.W., Suite 300
Washington, DC 20036
Cell: 215-850-2109
Fax: 202-429-8788

**Comment by tgirke** [comment]
I see. Most/many similarity algorithms, including MCS, are designed for (drug-like) organic compounds which is not the case here. The system should trigger a warning when using non-supported compounds. I will put this onto our to-do list.

**Comment by ToxRemeikas** [comment]
Got it.  Thank you for your time!

Deb Remeikas, M.A.
ToxServices
1367 Connecticut Ave, N.W., Suite 300
Washington, DC 20036
Cell: 215-850-2109
Fax: 202-429-8788
