### ISSUE TITLE
Clutering tool in chemmine

### ISSUE THREAD

**Issue by CarlZet** [girke-lab/chemminetools#254]
Hi, is there something wrong with the clustering tool in ChemMine? I have used i before, but this time all I receive after submitting a work is a message that an error occurred. Other functions seems to work fine though. Or does it work just fine, and it is me? Thank you. 

Best regards
Carl

**Comment by SimoneCulurgioni** [comment]
I have the same issue, thanks Carl for sharing this

**Comment by CarlZet** [comment]
Thank you. Let´s see if something can be done about it..

I tried to use "VERA" instead, but did not manage to get it working.. Back to the eyeballing method..

**Comment by tgirke** [comment]
This should be fixed...
